### ISSUE TITLE
区切りブロック：ドットスタイルが表示されない

### ISSUE THREAD

**Issue by t-hamano** [loos/arkhe#145]
WP6.5 → WP6.6で、スタイルが以下のように変わった事が原因だと思われます。

WP6.5:

```css
.wp-block-separator.is-style-dots {
    background: none !important;
    border: none;
    height: auto;
    line-height: 1;
    text-align: center;
}
```

WP6.6:

```css
.wp-block-separator.is-style-dots {
    background: none !important;
    border: none !important;
}
```

削除された `height:auto`をつけるだけで大丈夫そうです。
