### ISSUE TITLE
タグクラウドブロック：輪郭スタイルの時にborderが表示されなくなった

### ISSUE THREAD

**Issue by t-hamano** [loos/arkhe#146]
WP6.6でコアのCSSの詳細度が下がった事が影響していると思われます。

### WP6.5

![image](https://github.com/loos/arkhe/assets/54422211/6538933f-289f-4c35-a49d-065fc339f4d4)

```css
// コアのスタイル
.wp-block-tag-cloud.is-style-outline a {
  border: 1px solid;
}
// テーマのスタイル
.tag-cloud-link {
  border: none; // ←打ち消される
}
```

### WP6.6

![image](https://github.com/loos/arkhe/assets/54422211/75f07b3e-b8af-4aaa-afd2-4723474f20ea)

```css
// テーマのスタイル
.tag-cloud-link {
  border: none;
}
// コアのスタイル
.wp-block-tag-cloud.is-style-outline a {
  border: 1px solid; // ←打ち消される
}
```

テーマのスタイル（`.tag-cloud-link { border: none; }`）を削除するだけで良いかもしれません。
