### ISSUE TITLE
デバイスプレビューでの表示確認

### ISSUE THREAD

**Issue by t-hamano** [loos/arkhe#35]
クラシックテーマでもiframe化されるエディターインスタンス（デバイスプレビューのモバイル/タブレット）で表示・動作確認を行う。

**Comment by t-hamano** [comment]
モバイルタブレットプレビューのiframe内に `arkhe/dist/css/editor.css` は読み込まれているが、フォント系のセレクタ

```css
.block-editor .editor-styles-wrapper,
.blocks-widgets-container .editor-styles-wrapper {
    color: var(--ark-color_text);
    font-size: var(--ark-font_size, 16px);
    font-family: var(--ark-font_family);
    line-height: var(--ark-line_height, 1.8);
    background-color: var(--ark-color_bg);
}
```

が当たっていない。

「デバイスプレビューのiframeインスタンスは、bodyタグに直接 `.editor-styles-wrapper` クラスが不可されている」という特性を利用し、セレクタを追加します。

またメディアクエリも効くので、SP用フォントサイズも読み込むようにします。

![capture](https://user-images.githubusercontent.com/54422211/150488482-b922520e-b264-4244-b8d5-34c1a4f31e41.png)
